# Generated by Django 2.2.4 on 2020-08-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='testData',
            new_name='test_data',
        ),
        migrations.AddField(
            model_name='test',
            name='test_datasource',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='test',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
