# Generated by Django 2.2.4 on 2020-08-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200804_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCases', models.IntegerField(default=0)),
                ('newDailyCases', models.IntegerField(default=0)),
                ('totalDeaths', models.IntegerField(default=0)),
                ('newDailyDeaths', models.IntegerField(default=0)),
                ('yesterdaysCases', models.IntegerField(default=0)),
                ('rateIncrease', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
