# Generated by Django 2.2.4 on 2020-08-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='daysLeft',
            field=models.IntegerField(default=0),
        ),
    ]
