# Generated by Django 2.2.4 on 2020-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_covid_daysleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='rateIncrease',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
